# Generated by Django 6.0.6 on 2026-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='max_value',
            field=models.FloatField(blank=True, help_text='upper bound; leave empty for the last (open-ended) band', null=True),
        ),
    ]
